name = "vercel_gleam_runtime"
version = "1.0.0"
license = "MIT"
description = "A Vercel runtime that allows you to write functions in Gleam"
repository = { type = "github", user = "aslilac", repo = "vercel-gleam" }
target = "javascript"

[dependencies]
gleam_stdlib = "~> 0.20"
gleam_http = "~> 3.0"
